// Generated by tools/cut-mobs.ps1 - do not edit by hand
// rows in art/enemies/<id>.png: walk, attack, hit, death
const ART_META = { enemies: {
  gnome: { cw: 104, ch: 85, walk: 4, attack: 3, hit: 1, death: 2, big: [234, 220] },
  mushroom: { cw: 84, ch: 82, walk: 4, attack: 3, hit: 1, death: 2, big: [188, 220] },
  skeleton: { cw: 92, ch: 85, walk: 5, attack: 3, hit: 2, death: 1, big: [247, 220] },
  wolf: { cw: 98, ch: 90, walk: 3, attack: 3, hit: 1, death: 1, big: [234, 220] },
  roach: { cw: 130, ch: 86, walk: 3, attack: 3, hit: 1, death: 1, big: [260, 220] },
  crow: { cw: 107, ch: 89, walk: 3, attack: 2, hit: 2, death: 1, big: [255, 220] },
} };
