# Герои из слоёв FLARE (flare-game, CC-BY-SA 3.0) -> art/flare/hero_<id>.png + js/art-meta-flare-heroes.js
# Строки: стойка, бег, атака, смерть. Направление 5 (SE), порядок слоёв SE из engine/hero_layers.txt.
# Run: powershell -ExecutionPolicy Bypass -File tools/cut-flare-heroes.ps1
$ErrorActionPreference = 'Stop'
$game = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs", "$PSScriptRoot\FlareCut.cs" -ReferencedAssemblies System.Drawing
$fc = "$game\assets_src\flare\mods\fantasycore"; $out = "$game\art\flare"
$order = @('feet', 'legs', 'hands', 'main', 'chest', 'head', 'off')   # SE: первый — самый дальний
# герой: пол, атака (swing|cast|shoot), слоты
$heroes = [ordered]@{
  wanderer  = @('male', 'cast', @{ head = 'mage_hood'; chest = 'mage_vest'; hands = 'mage_sleeves'; legs = 'mage_skirt'; feet = 'mage_boots'; main = 'greatstaff' })
  scavenger = @('male', 'swing', @{ head = 'leather_hood'; chest = 'leather_chest'; hands = 'leather_gloves'; legs = 'leather_pants'; feet = 'leather_boots'; main = 'dagger'; off = 'buckler' })
  hunter    = @('female', 'shoot', @{ head = 'head_long'; chest = 'leather_chest'; hands = 'leather_gloves'; legs = 'leather_pants'; feet = 'leather_boots'; main = 'longbow' })
  vampire   = @('female_dark', 'cast', @{ head = 'mage_hood_alt2'; chest = 'mage_vest_alt2'; hands = 'mage_sleeves_alt2'; legs = 'mage_skirt_alt2'; feet = 'mage_boots_alt2'; main = 'wand' })
  guardian  = @('male', 'swing', @{ head = 'plate_helm'; chest = 'plate_cuirass'; hands = 'plate_gauntlets'; legs = 'plate_greaves'; feet = 'plate_boots'; main = 'longsword'; off = 'kite_shield' })
  pyro      = @('male', 'cast', @{ head = 'mage_hood_alt1'; chest = 'mage_vest_alt1'; hands = 'mage_sleeves_alt1'; legs = 'mage_skirt_alt1'; feet = 'mage_boots_alt1'; main = 'rod' })
  witch     = @('female', 'cast', @{ head = 'mage_hood'; chest = 'mage_vest'; hands = 'mage_sleeves'; legs = 'mage_skirt'; feet = 'mage_boots'; main = 'staff' })
  gambler   = @('male', 'shoot', @{ head = 'head_short'; chest = 'cloth_shirt'; hands = 'cloth_gloves'; legs = 'cloth_pants'; feet = 'cloth_sandals'; main = 'slingshot' })
  storm     = @('male', 'swing', @{ head = 'chain_coif'; chest = 'chain_cuirass'; hands = 'chain_gloves'; legs = 'chain_greaves'; feet = 'chain_boots'; main = 'war_hammer'; off = 'iron_buckler' })
  necro     = @('male', 'cast', @{ head = 'head_bald'; chest = 'mage_vest_alt2'; hands = 'mage_sleeves_alt2'; legs = 'mage_skirt_alt2'; feet = 'mage_boots_alt2'; main = 'greatstaff' })
}
$defaults = @{ chest = 'default_chest'; hands = 'default_hands'; legs = 'default_legs'; feet = 'default_feet' }
$meta = @()
foreach ($id in $heroes.Keys) {
  $h = $heroes[$id]; $gender = $h[0]; $slots = $h[2]
  $layers = New-Object 'System.Collections.Generic.List[System.Collections.Generic.Dictionary[string,FlareAnim]]'
  foreach ($t in $order) {
    $item = if ($slots.ContainsKey($t)) { $slots[$t] } elseif ($defaults.ContainsKey($t)) { $defaults[$t] } else { $null }
    if (-not $item) { continue }
    $txt = "$fc\animations\avatar\$gender\$item.txt"
    if (-not (Test-Path $txt)) { "  missing $gender/$item"; continue }
    $layers.Add([FlareCut]::Parse($txt, $fc))
  }
  $rows = @('stance', 'run', "$($h[1])|swing", 'die')
  $r = [FlareCut]::Composite($layers, $rows, 5, 8, 0.85, "$out\hero_$id.png"); [FlareCut]::ClearCache()
  $p = $r.Split(','); $meta += "  $($id): { cw: $($p[0]), ch: $($p[1]), ax: $($p[2]), ay: $($p[3]), rows: [$($p[4..($p.Length - 1)] -join ', ')] },"
  "$id : $r  ($([Math]::Round((Get-Item "$out\hero_$id.png").Length / 1KB)) KB)"
}
$js = "// Generated by tools/cut-flare-heroes.ps1 - do not edit by hand`n// FLARE hero sprites (flare-game, CC-BY-SA 3.0): rows idle, run, attack, death`nconst ART_FLARE_HEROES = {`n" + ($meta -join "`n") + "`n};`n"
[IO.File]::WriteAllText("$game\js\art-meta-flare-heroes.js", $js)
