# Cuts enemy sprites out of the concept sheets into art/enemies/.
# Usage: powershell -ExecutionPolicy Bypass -File tools/cut-mobs.ps1
# (ASCII only in code: PowerShell 5.1 reads files without BOM as ANSI; file names are found by pattern.)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs" -ReferencedAssemblies System.Drawing
$out = Join-Path $root 'art\enemies'
New-Item -ItemType Directory -Force $out | Out-Null

$sheets = Get-ChildItem $root -Filter *.png
# sheets are found by name: "anim..." (animations) and "moby..." (big art); Cyrillic built from char codes
$animWord = "$([char]0x0430)$([char]0x043D)$([char]0x0438)$([char]0x043C)"
$mobWord  = "$([char]0x043C)$([char]0x043E)$([char]0x0431)$([char]0x044B)"
$animFile = ($sheets | Where-Object { $_.Name -like "$animWord*" })[0].FullName
$bigFile  = ($sheets | Where-Object { $_.Name -like "$mobWord*" })[0].FullName
$anim = [Img]::Load($animFile)
$big  = [Img]::Load($bigFile)

# panel origin on the animation sheet (animation block, 512x265)
$panels = [ordered]@{ gnome = @(0, 225); mushroom = @(512, 225); skeleton = @(1024, 225); wolf = @(0, 720); roach = @(512, 720); crow = @(1024, 720) }
# rows: name = x, y, w, h (relative to panel), frame count
$rows = @{
  gnome    = @{ walk = @(12, 25, 240, 95, 4); attack = @(262, 20, 244, 100, 3); hit = @(262, 150, 100, 105, 1); death = @(368, 150, 140, 105, 2) }
  mushroom = @{ walk = @(12, 25, 238, 95, 4); attack = @(255, 25, 172, 95, 3); hit = @(238, 150, 104, 105, 1); death = @(352, 150, 155, 105, 2) }
  skeleton = @{ walk = @(12, 25, 245, 95, 5); attack = @(265, 25, 240, 95, 3); hit = @(222, 150, 150, 105, 2); death = @(372, 150, 135, 105, 1) }
  wolf     = @{ walk = @(12, 25, 245, 95, 3); attack = @(265, 25, 240, 95, 3); hit = @(280, 150, 88, 105, 1); death = @(386, 150, 120, 105, 1) }
  roach    = @{ walk = @(12, 25, 240, 95, 3); attack = @(262, 25, 245, 95, 3); hit = @(246, 150, 100, 105, 1); death = @(352, 150, 155, 105, 1) }
  crow     = @{ walk = @(12, 25, 245, 95, 3); attack = @(270, 25, 237, 95, 2); hit = @(226, 150, 140, 105, 2); death = @(372, 150, 135, 105, 1) }
}
# big static art: 3x2 grid of 512x512 cells
$cells = @{ gnome = @(0, 0); mushroom = @(512, 0); skeleton = @(1024, 0); wolf = @(0, 512); roach = @(512, 512); crow = @(1024, 512) }
$tol = @{ crow = 10 }   # the crow is almost as dark as the background

$meta = @()
foreach ($n in $panels.Keys) {
  $o = $panels[$n]; $t = if ($tol[$n]) { $tol[$n] } else { 18 }
  $p = $anim.Crop($o[0], $o[1], 512, 265)
  $m = [Cut]::BgMask($p, $t, 18, 18, 20)
  [Cut]::FillHoles($p, $m, 6, 20, 18, 18, 20)
  [Cut]::ApplyAlpha($p, $m, $t, 18, 18, 20)
  $all = @{}; $cw = 0; $ch = 0
  foreach ($a in 'walk', 'attack', 'hit', 'death') {
    $r = $rows[$n][$a]
    $f = [Cut]::SplitRow($m, $p.W, $r[0], $r[1], $r[2], $r[3], $r[4], 1)
    $all[$a] = $f
    for ($i = 0; $i -lt $f.Length; $i += 4) { $cw = [Math]::Max($cw, $f[$i + 2]); $ch = [Math]::Max($ch, $f[$i + 3]) }
  }
  # one sheet per mob: rows walk / attack / hit / death, equal cells
  $maxN = ($all.Values | ForEach-Object { $_.Length / 4 } | Measure-Object -Maximum).Maximum
  $sheet = New-Object Img; $sheet.W = $cw * $maxN; $sheet.H = $ch * 4; $sheet.P = New-Object byte[] ($sheet.W * $sheet.H * 4)
  $ri = 0; $counts = @()
  foreach ($a in 'walk', 'attack', 'hit', 'death') {
    $s = [Cut]::Strip($p, $all[$a], $cw, $ch)
    for ($y = 0; $y -lt $s.H; $y++) { [Array]::Copy($s.P, $y * $s.W * 4, $sheet.P, (($ri * $ch + $y) * $sheet.W) * 4, $s.W * 4) }
    $counts += ($all[$a].Length / 4); $ri++
  }
  $sheet.Save("$out\$n.png")
  # big art -> downscaled single image for bosses/elites
  $c = $cells[$n]; $cell = $big.Crop($c[0], $c[1], 512, 512)
  $bm = [Cut]::BgMask($cell, $t, 18, 18, 20)
  [Cut]::FillHoles($cell, $bm, 6, 250, 18, 18, 20)
  [Cut]::ApplyAlpha($cell, $bm, $t, 18, 18, 20)
  $comp = [Cut]::Components($bm, 512, 512, 4, 2000)
  $bi = 0; for ($i = 0; $i -lt $comp.Length; $i += 5) { if ($comp[$i + 4] -gt $comp[$bi + 4]) { $bi = $i } }
  $bx = $comp[$bi]; $by = $comp[$bi + 1]; $bw = $comp[$bi + 2]; $bh = $comp[$bi + 3]
  $fig = $cell.Crop($bx, $by, $bw, $bh)
  $k = [Math]::Min(1.0, 220.0 / $bh)
  $fig = [Cut]::Downscale($fig, [int]($bw * $k), [int]($bh * $k))
  $fig.Save("$out\${n}_big.png")
  $meta += "$n cell=${cw}x${ch} frames=$($counts -join ',') big=$($fig.W)x$($fig.H)"
}
$meta

# metadata for the game: js/art-meta.js
$js = "// Generated by tools/cut-mobs.ps1 - do not edit by hand`n// rows in art/enemies/<id>.png: walk, attack, hit, death`nconst ART_META = { enemies: {`n"
foreach ($line in $meta) {
  if ($line -match '^(\w+) cell=(\d+)x(\d+) frames=(\d+),(\d+),(\d+),(\d+) big=(\d+)x(\d+)') {
    $js += "  $($Matches[1]): { cw: $($Matches[2]), ch: $($Matches[3]), walk: $($Matches[4]), attack: $($Matches[5]), hit: $($Matches[6]), death: $($Matches[7]), big: [$($Matches[8]), $($Matches[9])] },`n"
  }
}
$js += "} };`n"
[IO.File]::WriteAllText((Join-Path $root 'js\art-meta.js'), $js)
