# Cuts boss art into art/bosses/ and writes js/art-meta-bosses.js.
#  Sheet 1 ("bossy art"): 4 single figures (2x2)          -> <id>.png
#  Sheet 2 ("bossy 2"):  10 bosses with animation poses   -> <id>.png (rows: forward, left, right, attack, death) + <id>_big.png (portrait)
# Figures on sheet 2 are found automatically (alpha > 60, components sorted left to right); numbers below are indices in that list.
# Usage: powershell -ExecutionPolicy Bypass -File tools/cut-bosses.ps1
# (ASCII only in code: PowerShell 5.1 reads files without BOM as ANSI; Cyrillic names are built from char codes.)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs" -ReferencedAssemblies System.Drawing
$out = Join-Path $root 'art\bosses'
New-Item -ItemType Directory -Force $out | Out-Null
$bossy = "$([char]0x0431)$([char]0x043E)$([char]0x0441)$([char]0x0441)$([char]0x044B)"
$art = "$([char]0x0430)$([char]0x0440)$([char]0x0442)"
$meta = @()

# ---------- sheet 1: single figures ----------
$im = [Img]::Load((Join-Path $root "$bossy $art.png"))
$m = [Cut]::AlphaMask($im, 60)
$singles = [ordered]@{ void = @(0, 0, 768, 512); shark = @(768, 0, 768, 512); minotaur = @(0, 500, 768, 524); deathknight = @(768, 500, 768, 524) }
foreach ($id in $singles.Keys) {
  $q = $singles[$id]
  $e = [Cut]::ExtractMain($im, $m, $q[0], $q[1], $q[2], $q[3], 14)
  $k = [Math]::Min(1.0, 300.0 / $e.H); $e = [Cut]::Downscale($e, [int]($e.W * $k), [int]($e.H * $k))
  $e.Save("$out\$id.png")
  $meta += "  $($id): { single: 1 },"
}

# ---------- sheet 2: animated bosses ----------
$im = [Img]::Load((Join-Path $root "$bossy 2.png"))
$m = [Cut]::AlphaMask($im, 60)
$c = [Cut]::Components($m, $im.W, $im.H, 2, 300)
$box = { param($i) @($c[$i * 5], $c[$i * 5 + 1], $c[$i * 5 + 2], $c[$i * 5 + 3]) }
# fwd / left / right / attack (list) / death (list) / big = portrait component (its name plate is cut off at the bottom)
# a frame can also be a half of a component: "57L" / "57R"
$anim = [ordered]@{
  flame_golem      = @{ fwd = 10; left = 5;  right = 15; attack = @(20, 25);    death = @(27, 33); big = 2 }
  spider_lord      = @{ fwd = 14; left = 8;  right = 18; attack = @(24, 30);    death = @(, 34);   big = 3 }
  crystal_beast    = @{ fwd = 12; left = 9;  right = 17; attack = @(23, 26);    death = @(, 32);   big = 0 }
  ancient_guardian = @{ fwd = 11; left = 7;  right = 19; attack = @(22, 29);    death = @(, 35);   big = 4 }
  sky_knight       = @{ fwd = 13; left = 6;  right = 16; attack = @(21, 28);    death = @(, 31);   big = 1 }
  ice_dragon       = @{ fwd = 49; left = 44; right = 52; attack = @('57L', '57R'); death = @(, 69); big = 36 }
  lich             = @{ fwd = 46; left = 41; right = 51; attack = @(56, 62);    death = @(, 67);   big = 39 }
  shadow_reaper    = @{ fwd = 50; left = 43; right = 54; attack = @(58, 63);    death = @(, 70);   big = 40 }
  void_lord        = @{ fwd = 48; left = 45; right = 55; attack = @(59, 64);    death = @(, 71);   big = 37 }
  hydra            = @{ fwd = 47; left = 42; right = 53; attack = @(60, 66);    death = @(, 68);   big = 38 }
}
$frame = {
  param($ref)
  $s = "$ref"; $half = ''
  if ($s -match '^(\d+)([LR])$') { $s = $Matches[1]; $half = $Matches[2] }
  $b = & $box ([int]$s)
  if ($half -eq 'L') { $b[2] = [int]($b[2] * 0.52) } elseif ($half -eq 'R') { $w2 = [int]($b[2] * 0.48); $b[0] += $b[2] - $w2; $b[2] = $w2 }
  [Cut]::ExtractMain($im, $m, $b[0], $b[1], $b[2], $b[3], 3)
}
foreach ($id in $anim.Keys) {
  $a = $anim[$id]
  $rows = [ordered]@{ fwd = @(& $frame $a.fwd); left = @(& $frame $a.left); right = @(& $frame $a.right); attack = @(); death = @() }
  foreach ($f in $a.attack) { $rows.attack += , (& $frame $f) }
  foreach ($f in $a.death) { $rows.death += , (& $frame $f) }
  $cw = 0; $ch = 0; foreach ($r in $rows.Keys) { foreach ($f in $rows[$r]) { $cw = [Math]::Max($cw, $f.W); $ch = [Math]::Max($ch, $f.H) } }
  $maxN = ($rows.Values | ForEach-Object { $_.Count } | Measure-Object -Maximum).Maximum
  $sheet = New-Object Img; $sheet.W = $cw * $maxN; $sheet.H = $ch * $rows.Count; $sheet.P = New-Object byte[] ($sheet.W * $sheet.H * 4)
  $ri = 0
  foreach ($r in $rows.Keys) { $ci = 0; foreach ($f in $rows[$r]) { [Cut]::Paste($sheet, $f, $ci * $cw + [int](($cw - $f.W) / 2), $ri * $ch + $ch - $f.H); $ci++ }; $ri++ }
  $sheet.Save("$out\$id.png")
  $b = & $box $a.big
  $big = [Cut]::ExtractMain($im, $m, $b[0], $b[1], $b[2], [int]($b[3] * 0.8), 6)   # the name plate sits in the bottom ~20%
  $big.Save("$out\${id}_big.png")
  $meta += "  $($id): { cw: $cw, ch: $ch, attack: $($rows.attack.Count), death: $($rows.death.Count) },"
}
$js = "// Generated by tools/cut-bosses.ps1 - do not edit by hand`n// art/bosses/<id>.png rows: forward, left, right, attack, death (single: 1 = one still image)`nconst ART_META_BOSSES = {`n" + ($meta -join "`n") + "`n};`n"
[IO.File]::WriteAllText((Join-Path $root 'js\art-meta-bosses.js'), $js)
$js
