# Cuts the three golems (fire / stone / water) from the golem sheet (white background) into art/enemies/.
# Every action on that sheet is a single pose, so each animation row holds 1-2 frames.
# Usage: powershell -ExecutionPolicy Bypass -File tools/cut-golems.ps1
# (ASCII only in code: PowerShell 5.1 reads files without BOM as ANSI; the sheet is found by a Cyrillic pattern built from char codes.)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs" -ReferencedAssemblies System.Drawing
$out = Join-Path $root 'art\enemies'
New-Item -ItemType Directory -Force $out | Out-Null
$W = 254
$golemWord = "$([char]0x0433)$([char]0x043E)$([char]0x043B)$([char]0x0435)$([char]0x043C)"   # "golem" in Russian
$file = (Get-ChildItem $root -Filter *.png | Where-Object { $_.Name -like "*$golemWord*" } | Sort-Object Length -Descending)[0].FullName

# Frames are [x0, x1] ranges inside the animation row (y = rowY .. rowY + rowH).
# Rows: walk, attack, hit, death, jump.  big = portrait area, blank = caption/palette areas to ignore.
$rowY = 642; $rowH = 140
$golems = [ordered]@{
  fire_golem = @{
    frames = [ordered]@{ walk = @(, @(10, 95)); attack = @(, @(95, 208)); hit = @(, @(10, 95)); death = @(@(293, 385), @(385, 488)); jump = @(, @(208, 293)) }
    big = @(0, 8, 490, 345); blank = @(@(0, 0, 183, 95), @(0, 95, 165, 200), @(438, 25, 35, 110))
  }
  stone_golem = @{
    frames = [ordered]@{ walk = @(, @(505, 588)); attack = @(, @(588, 702)); hit = @(, @(505, 588)); death = @(@(785, 893), @(893, 1000)); jump = @(, @(702, 785)) }
    big = @(505, 20, 495, 335); blank = @(@(505, 0, 185, 95), @(505, 95, 150, 200), @(955, 25, 30, 110))
  }
  water_golem = @{
    frames = [ordered]@{ walk = @(, @(1025, 1116)); attack = @(, @(1116, 1234)); hit = @(, @(1025, 1116)); death = @(@(1330, 1425), @(1425, 1530)); jump = @(, @(1234, 1330)) }
    big = @(1015, 8, 515, 350); blank = @(@(1015, 0, 150, 95), @(1015, 95, 160, 200), @(1472, 25, 30, 110))
  }
}

$im = [Img]::Load($file)
$m = [Cut]::BgMask($im, 30, $W, $W, $W)
[Cut]::FillHoles($im, $m, 8, 3, $W, $W, $W)
[Cut]::Defringe($im, $m, 70, 2, $W, $W, $W)
[Cut]::ApplyAlpha($im, $m, 60, $W, $W, $W)

$meta = @()
foreach ($id in $golems.Keys) {
  $g = $golems[$id]
  # captions and palette swatches are not part of the figures
  foreach ($z in $g.blank) { for ($y = $z[1]; $y -lt $z[1] + $z[3]; $y++) { for ($x = $z[0]; $x -lt $z[0] + $z[2]; $x++) { $m[$y * $im.W + $x] = $true } } }
  $rows = [ordered]@{}; $maps = @{}; $cw = 0; $ch = 0
  foreach ($a in $g.frames.Keys) {
    $boxes = @(); $fmaps = @()
    foreach ($fr in $g.frames[$a]) {
      $b = [Cut]::SplitByComp($m, $im.W, $fr[0], $rowY, $fr[1] - $fr[0], $rowH, 1, $null)
      $boxes += , $b; $fmaps += , @([Cut]::SlotMap, $fr[0], ($fr[1] - $fr[0]))
      $cw = [Math]::Max($cw, $b[2]); $ch = [Math]::Max($ch, $b[3])
    }
    $rows[$a] = $boxes; $maps[$a] = $fmaps
  }
  $maxN = ($rows.Values | ForEach-Object { $_.Count } | Measure-Object -Maximum).Maximum
  $sheet = New-Object Img; $sheet.W = $cw * $maxN; $sheet.H = $ch * $rows.Count; $sheet.P = New-Object byte[] ($sheet.W * $sheet.H * 4)
  $ri = 0; $counts = @()
  foreach ($a in $rows.Keys) {
    for ($i = 0; $i -lt $rows[$a].Count; $i++) {
      $fm = $maps[$a][$i]
      $s = [Cut]::StripSlots($im, $rows[$a][$i], $cw, $ch, $fm[0], $fm[1], $rowY, $fm[2])
      for ($y = 0; $y -lt $s.H; $y++) { [Array]::Copy($s.P, $y * $s.W * 4, $sheet.P, ((($ri * $ch + $y) * $sheet.W) + $i * $cw) * 4, $s.W * 4) }
    }
    $counts += "$($a): $($rows[$a].Count)"; $ri++
  }
  $sheet.Save("$out\$id.png")
  # portrait -> <id>_big.png (all figure pieces in the area, captions masked out)
  $bg = $g.big
  $pb = [Cut]::SplitByComp($m, $im.W, $bg[0], $bg[1], $bg[2], $bg[3], 1, $null)
  $pm = [Cut]::SlotMap
  $fig = [Cut]::StripSlots($im, $pb, $pb[2], $pb[3], $pm, $bg[0], $bg[1], $bg[2])
  $k = [Math]::Min(1.0, 240.0 / $fig.H)
  $fig = [Cut]::Downscale($fig, [int]($fig.W * $k), [int]($fig.H * $k))
  $fig.Save("$out\${id}_big.png")
  $meta += "  $($id): { cw: $cw, ch: $ch, $($counts -join ', ') },"
}
$js = "// Generated by tools/cut-golems.ps1 - do not edit by hand`n// rows in art/enemies/<id>.png: walk, attack, hit, death, jump`nObject.assign(ART_META.enemies, {`n" + ($meta -join "`n") + "`n});`n"
[IO.File]::WriteAllText((Join-Path $root 'js\art-meta-golems.js'), $js)
$js
