# Cuts the updated mob models (big sheet with 3 color variants per mob type) into art/enemies2/.
# Figures are found automatically (alpha > 200, connected components sorted left to right);
# the numbers below are indices in that list.
# Usage: powershell -ExecutionPolicy Bypass -File tools/cut-mobs2.ps1
# (ASCII only in code: PowerShell 5.1 reads files without BOM as ANSI.)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs" -ReferencedAssemblies System.Drawing
$dst = Join-Path $root 'art\enemies2'
New-Item -ItemType Directory -Force $dst | Out-Null

# the sheet name starts with "moby, golemy ..." (Cyrillic, built from char codes)
$prefix = "$([char]0x043C)$([char]0x043E)$([char]0x0431)$([char]0x044B),"
$file = (Get-ChildItem $root -Filter *.png | Where-Object { $_.Name -like "$prefix*" })[0].FullName
$im = [Img]::Load($file)
$m = [Cut]::AlphaMask($im, 200)                 # the sheet has a semi-transparent haze around figures
$c = [Cut]::Components($m, $im.W, $im.H, 2, 250)
$box = { param($i) @($c[$i * 5], $c[$i * 5 + 1], $c[$i * 5 + 2], $c[$i * 5 + 3]) }

# skin = walk frames, attack frames, big (main figure for elites/bosses); left = 1 if the frames face left.
# A negative frame number means "mirror this frame" (so all frames face the same way).
$skins = [ordered]@{
  fire_golem      = @{ walk = @(15);        attack = @(6);   big = 0 }
  stone_golem     = @{ walk = @(54);        attack = @(50);  big = 39 }
  water_golem     = @{ walk = @(87);        attack = @(89);  big = 75 }
  spider          = @{ walk = @(120, 117);  attack = @(127); big = 114 }
  spider_purple   = @{ walk = @(153, 155);  attack = @(166); big = 149 }
  spider_white    = @{ walk = @(189, 187);  attack = @(199); big = 186 }
  gnome           = @{ walk = @(17);        attack = @(38);  big = 2 }
  gnome_armored   = @{ walk = @(58);        attack = @(70);  big = 44 }
  mushroom        = @{ walk = @(125);       attack = @(118); big = 112 }
  mushroom_purple = @{ walk = @(161);       attack = @(152); big = 150 }
  mushroom_blue   = @{ walk = @(200);       attack = @(190); big = 188 }
  skeleton        = @{ walk = @(9, 18);     attack = @(29);  big = 1 }
  skeleton_green  = @{ walk = @(57, 62);    attack = @(47);  big = 43 }
  skeleton_blue   = @{ walk = @(94, 79);    attack = @(98);  big = 76 }
  wolf            = @{ walk = @(116, 129);  attack = @(146); big = 115 }
  wolf_red        = @{ walk = @(157, -171);  attack = @(160); big = 156 }
  wolf_blue       = @{ walk = @(194, 197);  attack = @(194); big = 192 }
  roach           = @{ walk = @(7, 22);     attack = @(37);  big = 22 }
  roach_green     = @{ walk = @(53);        attack = @(53);  big = 53 }
  roach_red       = @{ walk = @(104);       attack = @(104); big = 104 }
  crow            = @{ walk = @(145, 165, -181, -198); attack = @(183); big = 165; left = 1 }
}

$meta = @()
foreach ($id in $skins.Keys) {
  $s = $skins[$id]
  $rows = [ordered]@{ walk = @(); attack = @() }
  foreach ($a in 'walk', 'attack') { foreach ($i in $s[$a]) { $b = & $box ([Math]::Abs($i)); $f = [Cut]::ExtractMain($im, $m, $b[0], $b[1], $b[2], $b[3], 4); if ($i -lt 0) { $f = [Cut]::Mirror($f) }; $rows[$a] += , $f } }
  $cw = 0; $ch = 0; foreach ($a in $rows.Keys) { foreach ($f in $rows[$a]) { $cw = [Math]::Max($cw, $f.W); $ch = [Math]::Max($ch, $f.H) } }
  $maxN = [Math]::Max($rows.walk.Count, $rows.attack.Count)
  $sheet = New-Object Img; $sheet.W = $cw * $maxN; $sheet.H = $ch * 2; $sheet.P = New-Object byte[] ($sheet.W * $sheet.H * 4)
  $ri = 0
  foreach ($a in $rows.Keys) { $ci = 0; foreach ($f in $rows[$a]) { [Cut]::Paste($sheet, $f, $ci * $cw + [int](($cw - $f.W) / 2), $ri * $ch + $ch - $f.H); $ci++ }; $ri++ }
  $sheet.Save("$dst\$id.png")
  $b = & $box $s.big; $big = [Cut]::ExtractMain($im, $m, $b[0], $b[1], $b[2], $b[3], 4); $big.Save("$dst\${id}_big.png")
  $left = if ($s.left) { ", facesLeft: 1" } else { "" }
  $meta += "  $($id): { cw: $cw, ch: $ch, walk: $($rows.walk.Count), attack: $($rows.attack.Count)$left },"
}
$js = "// Generated by tools/cut-mobs2.ps1 - do not edit by hand`n// rows in art/enemies2/<skin>.png: walk, attack; <skin>_big.png - main figure`nconst ART_META2 = {`n" + ($meta -join "`n") + "`n};`n"
[IO.File]::WriteAllText((Join-Path $root 'js\art-meta-mobs2.js'), $js)
$js
