# Эффекты способностей FLARE (flare-game, CC-BY-SA 3.0) -> art/flare/fx_<name>.png (кадры в ряд) + js/art-meta-flare-fx.js
# Run: powershell -ExecutionPolicy Bypass -File tools/cut-flare-fx.ps1
$ErrorActionPreference = 'Stop'
$game = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs", "$PSScriptRoot\FlareCut.cs" -ReferencedAssemblies System.Drawing
$fc = "$game\assets_src\flare\mods\fantasycore"; $out = "$game\art\flare"
# имя, файл анимации, направление, масштаб
$fx = @(
  @('thunder', 'thunderstrike', 0, 0.45), @('blast', 'blast', 0, 0.5), @('heal', 'heal', 0, 0.6), @('freeze', 'freeze', 0, 0.8),
  @('quake', 'quake', 0, 0.6), @('spikes', 'spikes', 0, 0.55), @('knife', 'throw_knife', 4, 0.45), @('icicle', 'icicle', 4, 0.5),
  @('spark', 'spark_orange', 0, 0.6), @('spark_blue', 'spark_blue', 0, 0.6), @('plasma', 'plasmaball', 0, 0.5), @('mist', 'dark_mist', 0, 0.5),
  @('lightning', 'lightning', 0, 0.6), @('runes', 'runes', 0, 0.5), @('shield', 'shield', 0, 0.5), @('axe', 'throw_axe', 4, 0.45),
  @('rupture', 'rupture', 1, 0.55), @('rupture2', 'rupture', 2, 0.55)   # каменные шипы с лавой — Землетрясение (два варианта)
)
$meta = @()
foreach ($f in $fx) {
  $a = [FlareCut]::Parse("$fc\animations\powers\$($f[1]).txt", $fc)
  $r = [FlareCut]::Sheet($a, @('power'), $f[2], 12, $f[3], "$out\fx_$($f[0]).png"); [FlareCut]::ClearCache()
  $p = $r.Split(','); $meta += "  $($f[0]): { cw: $($p[0]), ch: $($p[1]), ax: $($p[2]), ay: $($p[3]), n: $($p[4]) },"
  "$($f[0]): $r"
}
$js = "// Generated by tools/cut-flare-fx.ps1 - do not edit by hand`n// FLARE power effects (flare-game, CC-BY-SA 3.0): frames in one row; ax/ay - anchor`nconst FLARE_FX = {`n" + ($meta -join "`n") + "`n};`n"
[IO.File]::WriteAllText("$game\js\art-meta-flare-fx.js", $js)
