# Монстры и боссы FLARE (flare-game, CC-BY-SA 3.0) -> art/flare/<model>.png + js/art-meta-flare.js
# Строки листа: ходьба, атака, получение урона, смерть. Направление 5 (вправо, чуть к камере).
# Исходники: assets_src/flare (git sparse-checkout flareteam/flare-game).
# Run: powershell -ExecutionPolicy Bypass -File tools/cut-flare.ps1
$ErrorActionPreference = 'Stop'
$game = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs", "$PSScriptRoot\FlareCut.cs" -ReferencedAssemblies System.Drawing
$fc = "$game\assets_src\flare\mods\fantasycore"; $ec = "$game\assets_src\flare\mods\empyrean_campaign"
$out = "$game\art\flare"; New-Item -ItemType Directory -Force $out | Out-Null
$rows = @('run|stance', 'swing|shoot|cast|dash_attack', 'hit|block', 'die|critdie')
# модель, мод, масштаб
$models = @(
  @('goblin', $fc, 0.7), @('goblin_elite', $fc, 0.8), @('skeleton', $fc, 0.7), @('skeleton_weak', $fc, 0.7), @('skeleton_archer', $fc, 0.7),
  @('skeleton_mage', $fc, 0.7), @('zombie', $fc, 0.7), @('antlion', $fc, 0.7), @('antlion_small', $fc, 0.7), @('fire_ant', $fc, 0.6),
  @('ice_ant', $fc, 0.6), @('minotaur', $fc, 0.6), @('wyvern', $fc, 0.6), @('wyvern_air', $fc, 0.6), @('wyvern_fire', $fc, 0.6), @('wyvern_water', $fc, 0.6),
  @('hobgoblin', $ec, 0.7), @('hobgoblin_archer', $ec, 0.7), @('antlion_armored', $ec, 0.8), @('skeleton_knight_boss', $ec, 0.9),
  @('skeleton_mage_boss', $ec, 0.9), @('skeleton_mage_high_boss', $ec, 0.9), @('wyvern_air_boss', $ec, 0.35), @('zombie_dark', $ec, 0.8)
)
$meta = @()
foreach ($m in $models) {
  $a = [FlareCut]::Parse("$($m[1])\animations\enemies\$($m[0]).txt", $m[1])
  $r = [FlareCut]::Sheet($a, $rows, 5, 8, $m[2], "$out\$($m[0]).png")
  [FlareCut]::ClearCache()
  $p = $r.Split(','); $meta += "  $($m[0]): { cw: $($p[0]), ch: $($p[1]), ax: $($p[2]), ay: $($p[3]), rows: [$($p[4..($p.Length - 1)] -join ', ')] },"
  "$($m[0]): $r  ($([Math]::Round((Get-Item "$out\$($m[0]).png").Length / 1KB)) KB)"
}
$js = "// Generated by tools/cut-flare.ps1 - do not edit by hand`n// FLARE sprites (flare-game, CC-BY-SA 3.0): rows walk, attack, hit, death; ax/ay - feet point in the cell`nconst ART_FLARE = {`n" + ($meta -join "`n") + "`n};`n"
[IO.File]::WriteAllText("$game\js\art-meta-flare.js", $js)
