# Снаряды и эффекты заклинаний -> art/flare/fx_<name>.png (кадры в ряд) + js/art-meta-spells.js
#  spell_animations — Viktor Hahn, CC-BY 4.0; FX — Mikodrak, CC0; sparkling_fireball_pack — rubberduck, CC0
# Run: powershell -ExecutionPolicy Bypass -File tools/cut-spells.ps1
$ErrorActionPreference = 'Stop'
$game = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs" -ReferencedAssemblies System.Drawing
$src = "$game\assets_src\spells"; $out = "$game\art\flare"
function Strip($frames, $size, $name) {       # frames: список Img одинакового размера -> ряд, каждый кадр уменьшен до size по большей стороне
  $f0 = $frames[0]; $k = [Math]::Min(1.0, $size / [Math]::Max($f0.W, $f0.H)); $cw = [Math]::Max(1, [int]($f0.W * $k)); $ch = [Math]::Max(1, [int]($f0.H * $k))
  $sheet = New-Object Img; $sheet.W = $cw * $frames.Count; $sheet.H = $ch; $sheet.P = New-Object byte[] ($sheet.W * $sheet.H * 4)
  for ($i = 0; $i -lt $frames.Count; $i++) { [Cut]::Paste($sheet, [Cut]::Downscale($frames[$i], $cw, $ch), $i * $cw, 0) }
  $sheet.Save("$out\fx_$name.png"); $script:meta += "  $($name): { cw: $cw, ch: $ch, n: $($frames.Count) },"; "$name $($frames.Count) x $cw x $ch"
}
function Grid($file, $cw, $ch, $size, $name, $from = 0, $to = 999, $step = 1) {   # сетка кадров; пустые кадры пропускаем
  $im = [Img]::Load("$src\spell_animations\$file.png"); $cols = [int]($im.W / $cw); $rows = [int]($im.H / $ch); $fr = @()
  for ($r = 0; $r -lt $rows; $r++) { for ($c = 0; $c -lt $cols; $c++) {
    $i = $r * $cols + $c; if ($i -lt $from -or $i -gt $to -or ($i - $from) % $step) { continue }
    $f = $im.Crop($c * $cw, $r * $ch, $cw, $ch); $h = [Cut]::AlphaHist($f); if ($h[0] -ge $cw * $ch - 20) { continue }; $fr += , $f } }
  Strip $fr $size $name
}
function Seq($dir, $size, $name, $step = 1) {   # папка с кадрами-файлами
  $files = Get-ChildItem "$src\$dir" -Filter *.png | Sort-Object { [int]([regex]::Match($_.BaseName, '(\d+)$').Groups[1].Value) }
  $fr = @(); $i = 0; foreach ($f in $files) { if ($i % $step -eq 0) { $fr += , ([Img]::Load($f.FullName)) }; $i++ }
  Strip $fr $size $name
}
function ExtraGrid($file, $cw, $ch, $size, $name, $step = 1, $anchor = $null, $skip = 0) {   # assets_src/extra: сетка кадров по строкам; anchor = @(доля x, доля y) точки привязки, skip — сколько первых кадров выбросить
  $im = [Img]::Load("$game\assets_src\extra\$file"); $cols = [int]($im.W / $cw); $rows = [int]($im.H / $ch); $fr = @(); $i = 0
  for ($r = 0; $r -lt $rows; $r++) { for ($c = 0; $c -lt $cols; $c++) {
    $f = $im.Crop($c * $cw, $r * $ch, $cw, $ch); $h = [Cut]::AlphaHist($f)
    if ($h[0] -ge $cw * $ch - 20) { continue }; if ($skip -gt 0) { $skip--; continue }; if ($i++ % $step) { continue }; $fr += , $f } }
  Strip $fr $size $name
  if ($anchor) { $m = $script:meta[-1]; $w = [int]([regex]::Match($m, 'cw: (\d+)').Groups[1].Value); $hh = [int]([regex]::Match($m, 'ch: (\d+)').Groups[1].Value)
    $script:meta[-1] = $m -replace ' n: ', " ax: $([int]($w * $anchor[0])), ay: $([int]($hh * $anchor[1])), n: " }
}
function ExtraSeq($dir, $size, $name, $from, $to, $step = 1) {   # assets_src/extra: папка с кадрами-файлами, только кадры from..to
  $files = Get-ChildItem "$game\assets_src\extra\$dir" -Filter *.png | Sort-Object Name
  $fr = @(); for ($i = $from; $i -le $to; $i += $step) { $fr += , ([Img]::Load($files[$i].FullName)) }
  Strip $fr $size $name
}
$meta = @()
Seq 'FX\fx7_energyBall' 48 'energy' 2
Seq 'FX\fx8_lighteningBall' 44 'lball' 1
Seq 'FX\fx10_blackExplosion' 80 'dark_boom' 1
Seq 'FX\fx4_sign_of_fire' 140 'fire_sign' 2
Seq 'sparkling_fireball_pack\particles_fireball_small' 96 'spark_fireball' 3
Grid 'flash01' 64 64 64 'star'
Grid 'flash_freeze' 512 512 140 'frost_burst' 0 95 3
Grid 'skull_smoke_green' 192 256 110 'skull_green'
Grid 'skull_smoke_purple' 192 256 110 'skull_purple'
Grid 'sphere_purple' 128 128 96 'vortex'
# assets_src/extra: «Teleporter effect» — rubberduck (CC0); удары и кровь — Sinestesia (CC0); «Leaf spell» — bart (CC-BY 3.0)
ExtraGrid 'teleporter-effect-blue_0.png' 240 320 104 'teleport' 4 @(0.5, 0.875)
ExtraGrid '2_75.png' 512 512 96 'crit_slash' 1 $null 2
ExtraGrid '1_128.png' 512 512 96 'blood'
ExtraGrid '0_16.png' 512 512 128 'blood_slash' 1 $null 1
ExtraSeq 'leafspell_1\leafspell' 100 'leaves' 14 37
$lv = [Img]::Load("$out\fx_leaves.png"); [Cut]::Gradient($lv, 150, 60, 10, 255, 214, 96, 2.6); $lv.Save("$out\fx_leaves.png")   # осенние листья: на траве зелёные не видно
$js = "// Generated by tools/cut-spells.ps1 - do not edit by hand`n// Spell FX: Viktor Hahn (CC-BY 4.0), Mikodrak (CC0), rubberduck (CC0), Sinestesia (CC0), bart (CC-BY 3.0); frames in one row`nconst SPELL_FX = {`n" + ($meta -join "`n") + "`n};`n"
[IO.File]::WriteAllText("$game\js\art-meta-spells.js", $js)
