# Границы фигуры в кадре покоя каждого героя FLARE (для карточки в меню: фигура целиком, без обрезки головы)
# -> js/art-meta-hero-cards.js. Запускать после tools/cut-flare-heroes.ps1
# Run: powershell -ExecutionPolicy Bypass -File tools/hero-card-box.ps1
$ErrorActionPreference = 'Stop'
$game = Split-Path $PSScriptRoot
Add-Type -Path "$PSScriptRoot\SpriteCut.cs" -ReferencedAssemblies System.Drawing
$meta = [IO.File]::ReadAllText("$game\js\art-meta-flare-heroes.js")
$out = @()
foreach ($m in [regex]::Matches($meta, '(\w+): \{ cw: (\d+), ch: (\d+)')) {
  $id = $m.Groups[1].Value; $cw = [int]$m.Groups[2].Value; $ch = [int]$m.Groups[3].Value
  $im = [Img]::Load("$game\art\flare\hero_$id.png")
  $x0 = $cw; $y0 = $ch; $x1 = -1; $y1 = -1
  for ($y = 0; $y -lt $ch; $y++) { for ($x = 0; $x -lt $cw; $x++) {
    if ($im.P[($y * $im.W + $x) * 4 + 3] -gt 24) { if ($x -lt $x0) { $x0 = $x }; if ($x -gt $x1) { $x1 = $x }; if ($y -lt $y0) { $y0 = $y }; if ($y -gt $y1) { $y1 = $y } } } }
  $out += "  $($id): [$x0, $y0, $($x1 - $x0 + 1), $($y1 - $y0 + 1)],"; "$id $x0,$y0 $($x1 - $x0 + 1)x$($y1 - $y0 + 1)"
}
$js = "// Generated by tools/hero-card-box.ps1 - do not edit by hand`n// Figure bounds [x, y, w, h] in the first idle frame of art/flare/hero_<id>.png`nconst HERO_CARD_BOX = {`n" + ($out -join "`n") + "`n};`n"
[IO.File]::WriteAllText("$game\js\art-meta-hero-cards.js", $js)
